# Site settings
title: Data Science Africa
location: Abuja, Nigeria (12 Nov - 16 Nov 2018)
city: Abuja
year: 2018
email: info@datascienceafrica.org
banner: Abuja06.jpg
description: > # this means to ignore newlines until "baseurl:"
  The 2018 Data Science Africa summer school held at African University of Science and Technology.
baseurl: "/dsa2018abuja" # the subpath of your site, e.g. /blog/
url: "http://www.datascienceafrica.org" # the base hostname & protocol for your site
twitter_username: datsciAfrica
logo_url: img/logo.png
github_username:  datsciafrica

other:
  url: /dsa2018/
  text: |
    <div class="" style="
                        font-weight: bold; 
                        font-size: 18px;

                        ">Kenya: Data Science Africa 2018</div>
    <div>June 04<sup>th</sup>  - June 08<sup>st</sup> 2018</div>
    <div>Nyeri, Kenya</div>

previous:
  url: /dsa2017/
  text: | # From here to "school:"
    <div class="" style="
                        font-weight: bold; 
                        font-size: 18px;

                        ">Previous: Data Science Africa 2017</div>
    <div>July 17<sup>th</sup>  - July 21<sup>st</sup> 2017</div>
    <div>Arusha, Tanzania</div>

social:
  title: Social Event
  text:
  
school:  
  name: Data Science in Africa School
  shortname: DSA2018
  location: "African University of Science and Technology, Abuja"
  googleformid: Y35RSOtJ2iCp0Szg2
  dates:		
  - 2018-11-12
  - 2018-11-13
  - 2018-11-14
  registration:
    deadline: 2018-08-04
    open: True
  draft: Y # set to Y if the programme is draft only.
  roles:
  - {type: Organizer, name: Prof. Amos David, url: "https://sites.google.com/site/cwamainadekut"}  
  - {type: Organizer, name: Mubangizi Martin Gordon, url: "http://air.ug/~mmubangizi"}
  - {type: Organizer, name: Charles I. Saidu, url: "http://air.ug/~jquinn"}
  - {type: Organizer, name: Samuel Grace Kehinde, url: "http://air.ug/~jquinn"}

conference:
  shortname: DSA2018
  theme: 
  hosts:
  roles:
  - {type: General Chair, name: Amos David, url: "", email: "adavid@aust.edu.ng"}
  - {type: Program Chair, name: Martin Mubangizi, url: "", email: "martin.mubangizi@one.un.org"}
  name: Data Science in Africa Workshop 
  location: "African University of Science and Technology, Abuja"
  googleformid: wiN1dJ1g7yPPXhEt2
  year: 2018
  month: November
  registration:
    deadline: 2018-08-15
    open: True
  # add other days here for them to appear
    abstract: 
      deadline: 2018-09-15
      googleformid: K3OxfLpKhn1wVOf02
  dates:	
  - 2018-11-15
  - 2018-11-16
  draft: Y # set to Y if the programme is draft only.
  organizers:
  - {logo: sheffield.png, name: University of Sheffield}
  - {logo: makerere.png, name: Makerere University}
  - {logo: plklogo.png, name: Pulse Lab Kampala}
  - {logo: dedan_kimathi.png, name: Dedan Kimathi University of Technology}
  - {logo: nmaist-logo.png, name: Nelson Mandela African Institute of Science and Technology}
  - {logo: aust.jpg, name: African University of Science and Technology, Abuja}
  goldsponsors: 
  #- {logo: facebook.png, name: "Facebook"}  
  #- {logo: google.png, name: "Google"}
  - {logo: arm-logo-blue-rgb.png, name: "ARM", url: "https://www.arm.com/"}
  #- {logo: ArmMbedLogo.png, name: "ARM mbed", url: "https://www.mbed.com/en/"}
  - {logo: Amazon-logo-RGB.png, name: "Amazon", url: "https://www.amazon.com/"}
  silversponsors:
  - {logo: deepmind_logo.png, name: "DeepMind", url: "https://deepmind.com/"}
  - {logo: Google.png, name: "Google", url: "https://www.google.com/"}

  
feedback: 




exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

sass:
    sass_dir: _scss

# Build settings
markdown: kramdown


analytics:
  google:
    tracking_id: UA-80484960-1

video:
  height: 315
  width: 560

future: true
